### PR TITLE
Verify nuget.exe download

### PR DESCRIPTION
**Pull request by saper**
Use embedded copies of root
certificates for api.nuget.org
and nuget.org.

Try wget, curl and /usr/bin/fetch
(included in FreeBSD base system)

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
Thanks! :+1:

**Comment by jasonwilliams200OK** [comment]
@dougbu, PTAL, we have experimented with FreeBSD and @saper came up with this changeset. It is more robust. It replaces `source` with `.` (period) and install nuget. We are digging some more and then I will make another PR to nuget upstream.

@emgarten, sorry I was busy with @saper to figure out and couldn't say for sure whether those were all the changes required. This changeset makes it quite better. The ultimate solution would be to have *all bash scripts* converted to native shell scripts: `/bin/sh` which is the standard. But we are half way through for now. :smile:

**Comment by dougbu** [comment]
@jasonwilliams200OK I don't have much context on this. What problem are you solving here?

**Comment by jasonwilliams200OK** [comment]
@dougbu, on Unices, there is this issue of having certificate installed on machine or else curl/wget throw error. https://github.com/dotnet/corefx/pull/2115 added the ability to fallback from curl->wget (reversed the preexisting order). But this very changeset added the ability to actually download and install the certificate for nuget and myget by making the downloading nuget.exe as a separate script function. It also added fallback for BSD's fetch, if both wget and curl are missing.

The second issue is on restoring the packages, for which `mozroots --install --sync` will fix the issue. I will add it subsequently.

The next issue which is preventing us building nuget3 on both Linux and FreeBSD is: 

```bash
Determining latest version
Latest version is 1.0.0-beta6-12114 
dnx-mono.1.0.0-beta6-12114 already installed. 
Adding /home/ubuntu/.dnx/runtimes/dnx-mono.1.0.0-beta6-12114/bin to process PATH
Updating alias 'default' to 'dnx-mono.1.0.0-beta6-12114'
info: Target default
info: Target pre-clean
info: Target target-dir-clean
info: Target build-clean
info: Target clean
info: Target post-clean
info: Target validate
info: Target restore-npm-modules
info: Target restore-bower-components
info: Target run-grunt
info: Target repo-initialize
info: Exec
info:   program: dnu
info:   commandline: restore
info:   workingdir: /home/ubuntu/workspace/src
warn: ApplicationName='dnu', CommandLine='restore', CurrentDirectory='/home/ubuntu/workspace/src', Native error= Cannot find the specified file
verbose: Stack trace: 
  at System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) [0x00000] in <filename unknown>:0 
  at System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) [0x00000] in <filename unknown>:0 
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) [0x00000] in <filename unknown>:0 
  at View3429a69d18b6466e939b0e51a92d0416.<RenderViewLevel0>m__15 () [0x00000] in <filename unknown>:0 
  at Sake.Engine.Builder.BuilderBase`1[System.Object].CallTarget (System.String name) [0x00000] in <filename unknown>:0 
  at Sake.Engine.Builder.BuilderBase`1[System.Object].StartingTarget (System.String name) [0x00000] in <filename unknown>:0 
  at View3429a69d18b6466e939b0e51a92d0416.<RenderViewLevel0>m__8 () [0x00000] in <filename unknown>:0 
  at Sake.Engine.Builder.BuilderBase`1[System.Object].CallTarget (System.String name) [0x00000] in <filename unknown>:0 
  at Sake.Engine.Builder.BuilderBase`1[System.Object].StartingTarget (System.String name) [0x00000] in <filename unknown>:0 
```

**Comment by saper** [comment]
Adding a whole set of certificates is a sensitive issue, since users may not really want this. (`mozroots --install` will even ask you one by one). One solution could be to import only the CAs needed to download; might be kind of hard to maintain. I am not sure if it is possible to supply a "temporary store" to let mono check certificates against.

**Pull request merged**
